AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  msvc

  Sample SAM Template for msvc

Globals:
  Function:
    Timeout: 60
    Layers:
      - !Ref NPMLayer
    Runtime: nodejs14.x
    MemorySize: 128
    Timeout: 60
    Layers:
      - !Ref NPMLayer

  Api:
    Cors:
      AllowHeaders: "'Content-Type, Authorization'"
      AllowOrigin: "'*'"
      MaxAge: "'0'"
      MinimumCompressionSize: 0
Resources:
  createProduct:
    DependsOn:
      - MSVCCatalogTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/organization/product/create.handler
      Description: A simple example includes a HTTP POST method to get all an item into DynamoDB table.
      CodeUri: ./lib
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MSVCCatalogTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /organization/{organizationId}/catalog
            Method: POST
            RestApiId: !Ref ApiGatewayApi

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !ImportValue Environment
      Description: !Ref ProjectSlug
      Models:
        ProductForCreate:
          type: object
          required:
            - name
            - pricePerUnit
            - unitOfMeasure
            - unit
            - category
            - subcategory
          properties:
            name:
              type: string
              description: "Product Name"
            description:
              type: string
              description: "Product Description"
            serviceArea:
              type: string
              description: "Product Category"
              enum: [ "KITCHEN", "BAR", "BAKERY" ]
            category:
              type: string
              description: "Product Category"
            subcategory:
              type: string
              description: "Product Category"
            barcode:
              type: string
              description: "Product Barcode"
            organizationProductCode:
              type: string
              description: "Organization specific Product Code"
            images:
              type: array
              description: "Product Images"
              items:
                type: object
                required:
                  - src
                properties:
                  default:
                    type: boolean
                  src:
                    type: string
            taxes:
              type: array
              description: "Taxes"
              items:
                type: object
                required:
                  - name
                  - tax_percent
                properties:
                  name:
                    type: string
                  tax_percent:
                    type: number
            pricePerUnit:
              type: number
              description: "Price per unit of the product"
            moq:
              type: number
              description: "Minimum Order Quantity"
            unit:
              type: string
              enum: [ "KILOGRAM", "GRAM", "MILLIGRAM", "POUNDS", "OUNCES", "MILLILITER", "LITER", "CC", "ITEM", "MILLIMETER", "CENTIMETER", "METER", "KILOMETER", "INCH", "FOOT", "YARD", "SECOND", "MINUTE", "HOUR", "DAY", "WEEK", "MONTH" ]
              description: "Unit of measure of the product"
            variations:
              type: array
              description: "Product Variations"
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: integer
            addons:
              type: array
              description: "Product Addons"
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  additionalPrice:
                    type: integer
            metaData:
              type: array
              description: "MetaData"
              items:
                type: object
                required:
                  - name
                  - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
        ProductForUpdate:
          type: object
          properties:
            name:
              type: string
              description: "Product Name"
            description:
              type: string
              description: "Product Description"
            serviceArea:
              type: string
              description: "Product Category"
              enum: [ "KITCHEN", "BAR", "BAKERY" ]
            category:
              type: string
              description: "Product Category"
            subcategory:
              type: string
              description: "Product Category"
            barcode:
              type: string
              description: "Product Barcode"
            organizationProductCode:
              type: string
              description: "Organization specific Product Code"
            taxes:
              type: array
              description: "Taxes"
              items:
                type: object
                required:
                  - name
                  - tax_percent
                properties:
                  name:
                    type: string
                  tax_percent:
                    type: number
            pricePerUnit:
              type: number
              description: "Price per unit of the product"
            moq:
              type: number
              description: "Minimum Order Quantity"
            unit:
              type: string
              enum: [ "KILOGRAM", "GRAM", "MILLIGRAM", "POUNDS", "OUNCES", "MILLILITER", "LITER", "CC", "ITEM", "MILLIMETER", "CENTIMETER", "METER", "KILOMETER", "INCH", "FOOT", "YARD", "SECOND", "MINUTE", "HOUR", "DAY", "WEEK", "MONTH" ]
              description: "Unit of measure of the product"
            variations:
              type: array
              description: "Product Variations"
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  price:
                    type: integer
            addons:
              type: array
              description: "Product Addons"
              items:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  additionalPrice:
                    type: integer
            metaData:
              type: array
              description: "MetaData"
              items:
                type: object
                required:
                  - name
                  - value
                properties:
                  name:
                    type: string
                  value:
                    type: string
        ImageForCreate:
          type: object
          required:
            - src
          properties:
            default:
              type: boolean
            src:
              type: string
        TaxForCreate:
          type: object
          required:
            - name
            - tax_percent
          properties:
            name:
              type: string
            tax_percent:
              type: number
      # Name: String
      # Tags: Map

  NPMLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies/

  MSVCCatalogTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "organizationIdIndex"
          KeySchema:
            - AttributeName: "organizationId"
              KeyType: HASH
            - AttributeName: "plu"
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: "catalogIdIndex"
          KeySchema:
            - AttributeName: "catalogId"
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      AttributeDefinitions:
        - AttributeName: "organizationId"
          AttributeType: "S"
        - AttributeName: "catalogId"
          AttributeType: "S"
        - AttributeName: "plu"
          AttributeType: "S"
        - AttributeName: "data"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "organizationId"
          KeyType: HASH
        - AttributeName: "data"
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: false
