AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  msvc

  Sample SAM Template for msvc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Layers:
      - !Ref NPMLayer

Resources:
  createProductFunction:
    DependsOn:
      - MSVCCatalogTable
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/organization-product-create.handler
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      CodeUri: ./dist
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MSVCCatalogTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /organization/{organizationId}/catalog
            Method: post

  NPMLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      # CompatibleRuntimes: List
      ContentUri: dependencies/
      # Description: String
      # LayerName: String
      # LicenseInfo: String
      # RetentionPolicy: Retain

  MSVCCatalogTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: 'organizationIdIndex'
          KeySchema:
            - AttributeName: 'organizationId'
              KeyType: HASH
            - AttributeName: 'plu'
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          # ProvisionedThroughput:
          #   ReadCapacityUnits: 2
          #   WriteCapacityUnits: 2
        - IndexName: 'catalogIdIndex'
          KeySchema:
            - AttributeName: 'catalogId'
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          # ProvisionedThroughput:
          #   ReadCapacityUnits: 2
          #   WriteCapacityUnits: 2
      AttributeDefinitions:
        - AttributeName: 'organizationId'
          AttributeType: 'S'
        - AttributeName: 'catalogId'
          AttributeType: 'S'
        - AttributeName: 'plu'
          AttributeType: 'S'
        - AttributeName: 'data'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'organizationId'
          KeyType: HASH
        - AttributeName: 'data'
          KeyType: RANGE
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 2
      #   WriteCapacityUnits: 2
      SSESpecification:
        SSEEnabled: false
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
  HelloWorldFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt HelloWorldFunctionRole.Arn
